pub mod depth_route;
pub mod earning_scraper;
pub mod swaps_scraper;
pub mod depths_scraper;
pub mod rune_pool_scraper;
pub mod swaps_route;
pub mod rpmuh_route;
pub mod earnings_route;
pub mod scraper_cron;